services:
  # BACKEND (NestJS)
  backend-dcash:
    build: 
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: backend-dcash
    ports:
      - "3001:3001"
    restart: always
    networks:
      - dcash-network
    environment:
      - FRONTEND_URL=https://dcash.dtasc.com.br
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=https://dcash.dtasc.com.br/api/auth/google/callback
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_HOST=redis-dcash
    depends_on:
      - redis-dcash

  # FRONTEND (Next.js)
  frontend-dcash:
    container_name: frontend-dcash
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: https://dcash.dtasc.com.br/api
    environment:
      - NEXT_PUBLIC_API_URL=https://dcash.dtasc.com.br/api
      - NEXTAUTH_URL=https://dcash.dtasc.com.br
      - NEXTAUTH_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dcash-network

  # REDIS CACHE
  redis-dcash:
    image: redis:alpine
    container_name: redis-dcash
    networks:
      - dcash-network
    restart: always

  # MARKET-SERVICE
  market-service:
    build: 
      context: .
      dockerfile: apps/market-service/Dockerfile
    container_name: market-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis-dcash
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - redis-dcash
    networks:
      - dcash-network
    restart: always

networks:
  dcash-network:
    driver: bridge