server {
    listen 80;
    server_name dcash.dtasc.com.br;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name dcash.dtasc.com.br;

    ssl_certificate /etc/nginx/certs/live/dcash.dtasc.com.br/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/dcash.dtasc.com.br/privkey.pem;

    # Otimizações de SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # FRONTEND
    location / {
        proxy_pass http://frontend-dcash:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # BACKEND
    location /api {
        proxy_pass http://backend-dcash:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Proto https;
    }

    # MARKET-SERVICE
    location /api/market {
    proxy_pass http://market-service:8000; # Direciona para o Python
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
}
}